logging:
    level:
        org.springframework.ai: INFO
# Spring Boot Actuator - GCP uses /health
management:
    endpoints:
        web:
            exposure:
                include: health,info
    endpoint:
        health:
            show-details: always
# Server port (useful for local testing, GCP Cloud Functions can use this as well)
server:
    port: 8080
spring:
    codec:
        max-in-memory-size: 1MB
    threads:
        virtual:
            enabled: true
    # web clients that interact will LLM needs more patience
    http:
        client:
            reactive:
              read-timeout: 20s
              connect-timeout: 5s
              response-timeout: 120s
    # Claude API Configuration
    ai:
        retry:
            max-attempts: 5
        anthropic:
            api-key: ${CLAUDE_API_KEY:}
            chat:
                options:
                    model: claude-opus-4-20250514
                    temperature: 0.7
                    max-tokens: 500
        mcp:
            client:
                enabled: false
                initialized: false
                request-timeout: 30s
                name: dataflow-tools
                toolcallback:
                    enabled: false
                sse:
                    connections:
                        gcptoolbox:
                            url: ${MCPSERVER_URL:}
                            sse-endpoint: /sse
